{"name": "Проверка ошибки при получении заказа с несуществующим номером", "status": "passed", "steps": [{"name": "Попытка получить заказ с несуществующим track номером", "status": "passed", "start": 1760865227041, "stop": 1760865227416}], "start": 1760865227041, "stop": 1760865227417, "uuid": "a8342312-424f-4b18-bb90-ac1e839d67f3", "historyId": "72d6d31edade871ba10cfac18b83a2e0", "testCaseId": "72d6d31edade871ba10cfac18b83a2e0", "fullName": "tests.tests_orders.test_order_get_by_track.TestOrderGetByTrack#test_order_get_by_track_error_with_wrong_track", "labels": [{"name": "parentSuite", "value": "tests.tests_orders"}, {"name": "suite", "value": "test_order_get_by_track"}, {"name": "subSuite", "value": "TestOrderGetByTrack"}, {"name": "host", "value": "Sergei"}, {"name": "thread", "value": "5332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_orders.test_order_get_by_track"}], "titlePath": ["tests", "tests_orders", "test_order_get_by_track.py", "TestOrderGetByTrack"]}