{"name": "Проверка получения ошибки при повторном использовании логина для создания курьера", "status": "passed", "description": "Проверяются код и тело ответа.", "steps": [{"name": "Попытка создания второго курьера с тем же логином", "status": "passed", "start": 1760866180699, "stop": 1760866181148}], "start": 1760866180699, "stop": 1760866181149, "uuid": "14ef7380-57b0-4c15-a988-313dc24db940", "historyId": "fa8dadfcce5ef2dd1fdd6c75ddb29064", "testCaseId": "fa8dadfcce5ef2dd1fdd6c75ddb29064", "fullName": "tests.tests_couriers.test_courier_create.TestCourierCreate#test_create_courier_account_login_conflict", "labels": [{"name": "parentSuite", "value": "tests.tests_couriers"}, {"name": "suite", "value": "test_courier_create"}, {"name": "subSuite", "value": "TestCourierCreate"}, {"name": "host", "value": "Sergei"}, {"name": "thread", "value": "9908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_couriers.test_courier_create"}], "titlePath": ["tests", "tests_couriers", "test_courier_create.py", "TestCourierCreate"]}